---
output: word_document
bibliography: kenosee-white-bear.bib
csl: freshwater-biology.csl
---

All statistical analyses were performed in `R` [version 4.0.4, @r_core_team_r_2021]. The `tidyr` and `dplyr` packages [@wickham_tidyr_2021, @wickham_dplyr_2021] were used for data wrangling, while plots were created using the `ggplot2` and `cowplot` packages [@wickham_ggplot2_2016, @wilke_cowplot_2020]. The code is available on GitHub at https://github.com/simpson-lab/kenosee-white-bear.

Sediment age-depth relationships were estimated using shape-constrained additive models (SCAMs) with monotone decreasing P-splines via the `scam` package [@pya_scam_2021] with generalized cross-validation (GCV) smoothness parameter selection. Trends in pigment and other geochemical proxies were estimated using generalized additive models (GAMs) using the `mgcv` package [@wood_fast_2011; @wood_generalized_2017; @simpson_modelling_2018]. Specifically, pigment concentrations were estimated using a hierarchical generalized additive model [HGAM; see @pedersen_hierarchical_2019]. The HGAM used a Gamma location-scale family which allowed to estimate the trends in the concentrations' mean and variance [@wood_smoothing_2016]. The mean concentration was modelled using a global smooth of year and a factor smooth for each combination of the 2 lakes and 10 pigments, for a total of 20 factors (model *GS* sensu @pedersen_hierarchical_2019). The shape term of the distribution was modelled using the same terms as above with the addition of a smooth of each slice's log-transformed interval. This last term accounted for the differences in information between slices, since slices which averaged more years were expected to be less variable (i.e. more stable). Observations were weighted by the (standardized) interval of the sample. The smoothness parameter of the model was estimated using restricted maximum likelihood (*REML*, see @simpson_modelling_2018). The variance was then estimated by calculating the product of the mean and shape parameter estimates. Uncertainty around the variance estimate was calculated using 95% Bayesian credible intervals which were obtained by running 10,000 simulations and taking the 0.025% and 97.5% quantiles of the posterior distribution.

The chlorophyll:pheophytin ratio and diatom-inferred UV indexes were modelled using HGAMs with a Gamma and Tweedie family, respectively. The Tweedie response distribution was used for the UV index because of the presence of zeros, which are not supported by the Gamma distribution (i.e. the Gamma distribution is for strictly positive numbers). Both models used a smooth of year by lake, such that each lake had a different smoothness parameter (model *I* sensu @pedersen_hierarchical_2019). As with the pigment models, these two models also used REML and observations were weighted by the (standardized) interval of the sample.

To identify periods of significant change, the first derivative of the estimated smooth trend was evaluated for each proxy from the relevant model [@bennion_assessing_2015; @simpson_modelling_2018]. The first derivative was estimated using functions built with the `gratia` package [@simpson_gratia_2021]. Periods of significant change were identified as periods where the credible interval of the estimated derivative excluded 0 at the $\alpha = 0.05$ level of significance.

***ask Gavin to add some text regarding derivatives*** $\uparrow$

# References
